/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateHomeworkUI.java
 *
 * Created on Apr 5, 2013, 10:52:18 PM
 */
package GUI;

import Core.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashoraya
 */
public class CreateHomeworkUI extends javax.swing.JFrame {

    /** Creates new form CreateHomeworkUI */
    public CreateHomeworkUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        minProblemRangeTextField = new javax.swing.JTextField();
        numberOfProblemsTextField = new javax.swing.JTextField();
        assignmentNumberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maxProblemRangeTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        additionCheckBox = new javax.swing.JCheckBox();
        subtractionCheckBox = new javax.swing.JCheckBox();
        multiplicationCheckBox = new javax.swing.JCheckBox();
        divisionCheckBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEAT - Create Homework Assignment");
        setResizable(false);

        jLabel1.setText("Assignment Number:");

        jLabel2.setText("Number of Problems:");

        jLabel3.setText("Problem Value Range:");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        minProblemRangeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minProblemRangeTextFieldActionPerformed(evt);
            }
        });

        assignmentNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("-");

        jLabel5.setText("Problem Types:");

        additionCheckBox.setText("Addition");
        additionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionCheckBoxActionPerformed(evt);
            }
        });

        subtractionCheckBox.setText("Subtraction");

        multiplicationCheckBox.setText("Multiplication");

        divisionCheckBox.setText("Division");

        jMenu1.setText("Options");

        logoutButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jMenu1.add(logoutButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minProblemRangeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(numberOfProblemsTextField)
                                    .addComponent(assignmentNumberTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maxProblemRangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(additionCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(subtractionCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(multiplicationCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(divisionCheckBox)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(assignmentNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfProblemsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(minProblemRangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(maxProblemRangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(additionCheckBox)
                    .addComponent(subtractionCheckBox)
                    .addComponent(multiplicationCheckBox)
                    .addComponent(divisionCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(createButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(406, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.LOGIN).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        TeacherProfile teacher = UserManager.instance.getCurrentUserAsTeacherProfile();
        int assignmentNumber = Integer.parseInt(assignmentNumberTextField.getText());
        int numberOfProblems = Integer.parseInt(numberOfProblemsTextField.getText());
        int minOperand = Integer.parseInt(minProblemRangeTextField.getText());
        int maxOperand = Integer.parseInt(maxProblemRangeTextField.getText());
        boolean add = additionCheckBox.isSelected();
        boolean sub = subtractionCheckBox.isSelected();
        boolean mul = multiplicationCheckBox.isSelected();
        boolean div = divisionCheckBox.isSelected();
        Response addHomeworkAssignmentResponse = teacher.addHomeworkAssignment(assignmentNumber, numberOfProblems, minOperand, maxOperand, add, sub, mul, div);
        if(addHomeworkAssignmentResponse.success == true) 
        {
            Response updateTeacherUserResponse = UserManager.instance.updateAndSaveTeacherUser(teacher);
            if(updateTeacherUserResponse.success == true)
            {
                JOptionPane.showMessageDialog(this, "Homework assignment has been successfully created.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, updateTeacherUserResponse.failureMessage);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, addHomeworkAssignmentResponse.failureMessage);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void minProblemRangeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minProblemRangeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minProblemRangeTextFieldActionPerformed

    private void assignmentNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentNumberTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.LOGIN).setVisible(true);
        this.setVisible(false);
        assignmentNumberTextField.setText("");
        numberOfProblemsTextField.setText("");
        minProblemRangeTextField.setText("");
        maxProblemRangeTextField.setText("");
    }//GEN-LAST:event_backButtonActionPerformed

    private void additionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additionCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateHomeworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateHomeworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateHomeworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateHomeworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateHomeworkUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox additionCheckBox;
    private javax.swing.JTextField assignmentNumberTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JCheckBox divisionCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logoutButton;
    private javax.swing.JTextField maxProblemRangeTextField;
    private javax.swing.JTextField minProblemRangeTextField;
    private javax.swing.JCheckBox multiplicationCheckBox;
    private javax.swing.JTextField numberOfProblemsTextField;
    private javax.swing.JCheckBox subtractionCheckBox;
    // End of variables declaration//GEN-END:variables
}
