/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentMainMenuUI.java
 *
 * Created on Apr 5, 2013, 8:42:20 PM
 */
package GUI;

import Core.UserManager;
import Core.StudentProfile;
import java.awt.Font;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Ashoraya
 */
public class StudentMainMenuUI extends javax.swing.JFrame {

    /** Creates new form StudentMainMenuUI */
    public StudentMainMenuUI() {
        initComponents();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
                public void componentHidden(java.awt.event.ComponentEvent evt) 
                {
                    //componentHidden(evt);
                }
                public void componentShown(java.awt.event.ComponentEvent evt) {
                    studentMainMenuUIComponentShown(evt);
                }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        homeworkAssignmentsButton = new javax.swing.JButton();
        studyProblemsButton = new javax.swing.JButton();
        progressReportButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        logoutButton = new javax.swing.JMenu();
        logoutButtonPressed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEAT - Main Menu");
        setResizable(false);

        homeworkAssignmentsButton.setText("Homework Assignments");
        homeworkAssignmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeworkAssignmentsButtonActionPerformed(evt);
            }
        });

        studyProblemsButton.setText("Practice Problems");
        studyProblemsButton.setMaximumSize(new java.awt.Dimension(143, 23));
        studyProblemsButton.setMinimumSize(new java.awt.Dimension(143, 23));
        studyProblemsButton.setPreferredSize(new java.awt.Dimension(143, 23));
        studyProblemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyProblemsButtonActionPerformed(evt);
            }
        });

        progressReportButton.setText("Progress Report");
        progressReportButton.setMaximumSize(new java.awt.Dimension(143, 23));
        progressReportButton.setMinimumSize(new java.awt.Dimension(143, 23));
        progressReportButton.setPreferredSize(new java.awt.Dimension(143, 23));
        progressReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressReportButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome Message");

        logoutButton.setText("Options");

        logoutButtonPressed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutButtonPressed.setText("Logout");
        logoutButtonPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonPressedActionPerformed(evt);
            }
        });
        logoutButton.add(logoutButtonPressed);

        jMenuBar1.add(logoutButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studyProblemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeworkAssignmentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(progressReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addGap(0, 155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(homeworkAssignmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studyProblemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        setSize(new java.awt.Dimension(648, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentMainMenuUIComponentShown(ComponentEvent evt) {
        jLabel1.setFont(new Font("Serif", Font.PLAIN, 32));
        StudentProfile student = UserManager.instance.getCurrentUserAsStudentProfile();
        jLabel1.setText("Welcome back " + student.getUsername() + "!");
    }
    private void progressReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressReportButtonActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.STUDENTPROGRESSREPORT).setVisible(true);
    }//GEN-LAST:event_progressReportButtonActionPerformed

    private void homeworkAssignmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeworkAssignmentsButtonActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.HOMEWORK).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeworkAssignmentsButtonActionPerformed

    private void studyProblemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyProblemsButtonActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.STUDY).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studyProblemsButtonActionPerformed

    private void logoutButtonPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonPressedActionPerformed
        WindowManager.GetWin(WindowManager.WINDOWS.LOGIN).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonPressedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StudentMainMenuUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeworkAssignmentsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JMenuItem logoutButtonPressed;
    private javax.swing.JButton progressReportButton;
    private javax.swing.JButton studyProblemsButton;
    // End of variables declaration//GEN-END:variables
}
